exports.bs = function( bs ){
	if( bs.$os( 'hostname' ) == 'tony-VirtualBox' ){
		bs.db( 'local' ).$( 'url', 'localhost:3306', 'id', 'root', 'pw', '1234', 'db', 'hika01' );
	}else{
		bs.db( 'local' ).$( 'url', '10.0.0.1:3306', 'id', 'hika01', 'pw', 'projectbs00', 'db', 'hika01' );
	}
	bs.sql( 'list' ).$( 'db', 'local', 'query', 'select k,v from web,user where user_rowid=rowid and userid=@userid@' );
};