module.exports = {
	// image
	'jpeg' :'image/jpeg',
	'jpg'  :'image/jpeg',
	'gif'  :'image/gif',
	'png'  :'image/png',
	// text
	'html' :'text/html',
	'htm'  :'text/html',
	'js'   :'text/javascript',
	'css'  :'text/css',
	// video
	'3gp'  :'video/3gpp',
	'3g2'  :'video/3gpp2',
	'h261' :'video/h261',
	'h263' :'video/h263',
	'h264' :'video/h264',
	'jpgv' :'video/jpeg',
	'jpm'  :'video/jpm',
	'jpgm' :'video/jpm',
	'mj2'  :'video/mj2',
	'mjp2' :'video/mj2',
	'mp4'  :'video/mp4',
	'mp4v' :'video/mp4',
	'mpg4' :'video/mpg4',
	'mpeg' :'video/mpeg',
	'mpg'  :'video/mpeg',
	'mpe'  :'video/mpeg',
	'm1v'  :'video/mpeg',
	'm2v'  :'video/mpeg',
	'ogv'  :'video/ogg',
	'qt'   :'video/quicktime',
	'mov'  :'video/quicktime',
	'mxu'  :'video/vnd.mpegurl',
	'm4u'  :'video/vnd.mpegurl',
	'asf'  :'video/x-ms-asf',
	'asx'  :'video/x-ms-asf',
	'wm'   :'video/x-ms-wm',
	'wmv'  :'video/x-ms-wmv',
	'wmx'  :'video/x-ms-wmx',
	'wvx'  :'video/x-ms-wvx',
	'avi'  :'video/x-msvideo',
	'movie':'video/x-sgi-movie',
	// audio
	'oga':'audio/ogg',
	'ogg':'audio/ogg',
	'spx':'audio/ogg',
	'mp4a' :'audio/mp4',
	'mpga' :'audio/mpeg',
	'mp2'  :'audio/mpeg',
	'mp2a' :'audio/mpeg',
	'mp3'  :'audio/mpeg',
	'm2a'  :'audio/mpeg',
	'm3a'  :'audio/mpeg',
	'mid'  :'audio/midi',
	'midi' :'audio/midi',
	'kar'  :'audio/midi',
	'rmi'  :'audio/midi',
	'wav'  :'audio/wav',
	'aif'  :'audio/x-aiff',
	'aifc' :'audio/x-aiff',
	'aiff' :'audio/x-aiff',
	'm3u'  :'audio/x-mpegurl',
	'wma'  :'audio/x-ms-wma',
	'wax'  :'audio/x-ms-wax',
	'wav'  :'audio/x-wav'
};
